table:
  class: table
  shape: table
  color: table
  size: s_table
  weight: w_table
cracker:
  class: cracker
  shape: box
  color: red
  size: s_large
  weight: w_light
meat:
  class: meat
  shape: cylinder
  color: blue
  size: s_small
  weight: w_medium
mustard:
  class: mustard
  shape: complex
  color: yellow
  size: s_medium
  weight: w_heavy
soup:
  class: soup
  shape: cylinder
  color: red
  size: s_small
  weight: w_medium
sugar:
  class: sugar
  shape: box
  color: white
  size: s_medium
  weight: w_heavy
bleach:
  class: bleach
  shape: complex
  color: white
  size: s_large
  weight: w_heavy
gelatin:
  class: gelatin
  shape: box
  color: red
  size: s_small
  weight: w_light
apple:
  class: apple
  shape: complex
  color: red
  size: s_small
  weight: w_light
chips:
  class: chips
  shape: cylinder
  color: red
  size: s_large
  weight: w_medium
coffee:
  class: coffee
  shape: cylinder
  color: blue
  size: s_large
  weight: w_heavy
tuna:
  class: tuna
  shape: cylinder
  color: blue
  size: s_small
  weight: w_medium
