#!/usr/bin/env python
# In project imports
import srp_md
import srp_md.ui as ui
from srp_md import srp_md_log

# Ros imports
import rospy

# Python imports
import logging

# Get a logger
loger = logging.getLogger('srp_md')


def main():
    # Setup ros
    rospy.init_node('srp_md')

    # Define the srp
    srp = srp_md.SrpMd()

    # Define user interface
    ctrl = ui.Controller(srp)
    view = ui.TermView(srp, ctrl)

    # Run
    r = rospy.Rate(100)
    while not rospy.is_shutdown():
        view.run()
        r.sleep()


if __name__ == '__main__':
    loger.debug('System starting up... #BOLD')
    try:
        main()
    finally:
        loger.debug('System shuting down... #BOLD')
